In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import re
import numpy as np

In [2]:
import sys
sys.getdefaultencoding()

'utf-8'

Open the questionnaire file (word document version of the questionnaire saved as html):

In [3]:
questionnaire_file = open("FF_f1_Questionnaire_2013.htm", "r")

In [4]:
soup=BeautifulSoup(questionnaire_file, "html.parser")

In [5]:
ps=[p for p in soup.find_all('p')]

In [6]:
ps[164:168]

[<p class="MsoNormal" style="margin-left:1.0in;line-height:150%;text-autospace:
 none"><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'>YES, MARRIED TO MOTHER..................... 1 <b>(SKIP TO B22 ON
 P.14)</b></span></p>,
 <p class="MsoNormal" style="margin-left:1.0in;line-height:150%;text-autospace:
 none"><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'>NO, NOT MARRIED TO MOTHER.............. 2 </span></p>,
 <p class="MsoNormal" style="line-height:150%;text-autospace:none"><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'> </span></p>,
 <p class="MsoNormal" style="text-autospace:none"><span style="position:relative;
 z-index:251606016"><span style="position:absolute;left:-1px;top:-1px;
 width:566px;height:3px"><img height="3" src="FF_f1_Questionnaire_2013_files/image007.gif" width="566"/></span></span><b><span style='font-size:11.0pt;font-family:"Arial",sans-serif;color:black'> </span></b></p>]

Opening the excel file with all the questions for p6, using the pandas python library:

In [7]:
df=pd.read_excel("FFCf1.xlsx") #this is an excel file with all the questions for p6

In [8]:
df.head()

   position   name                                             varlab
0        15   f1a2                     Were you present at the birth?
1        16   f1a3                           Have you held baby(ies)?
2        17   f1a4            Will the baby(ies) have your last name?
3        18  f1a4a  Did you want the baby(ies) to have your last n...
4        19   f1a5        Will your name be on the birth certificate?

In [9]:
df.shape

(337, 3)

In [10]:
reg = re.compile(r'(?P<section>[A-Za-z]*\d*)(?P<rest>.*)')

def format_q_num(name):
    """takes in the question numbers in the name column and outputs them in the format
    they appear in the text"""
    name=name.lstrip('f1')
    name=reg.search(name)
    section=name.group('section').upper()
    rest=name.group('rest').upper()
    return section+rest

In [11]:
df['question_number']=df.name.apply(lambda x: format_q_num(x))

In [18]:
df['multiple_answers']=df.question_number.apply(lambda x: 1 if re.match('[A-Z]\d*[A-Z]\d*',x) else 0) 
#adds a column where 1 indicates that it is one of the questions with multiple entries in the data frame
#I think these are mostly (only?) the "select all that apply" questions

In [19]:
df

,position,name,varlab,question_number,multiple_answers
0,15,f1a2,Were you present at the birth?,A2,0
1,16,f1a3,Have you held baby(ies)?,A3,0
2,17,f1a4,Will the baby(ies) have your last name?,A4,0
3,18,f1a4a,Did you want the baby(ies) to have your last n...,A4A,1
4,19,f1a5,Will your name be on the birth certificate?,A5,0
5,20,f1a5a,Did you want your name on the birth certificate?,A5A,1
6,21,f1a6,Do you have other biological children?,A6,0
7,22,f1a6a,How many other biological children?,A6A,1
8,23,f1a7,Who (does/do) the (baby/babies) look like?,A7,0
9,24,cf1age,Constructed - Father's age (years),CF1AGE,1
10,25,f1b1a,How many years did you know each other before ...,B1A,1
11,26,f1b1b,How many months did you know each other before...,B1B,1
12,27,f1b2,Is respondent married to baby's mother?,B2,0
13,28,f1b3,What describes your current relationship with ...,B3,0
14,29,f1b4a,"Why did romantic rel end with BM, Financial Re...",B4A,1
15,30,f1b4b,"Why did romantic rel end with BM, Distance (Do...",B4B,1
16,31,f1b4c,"Why did romantic rel end with BM, Incarceration ?",B4C,1
17,32,f1b4d,"Why did romantic rel end with BM, Relationship...",B4D,1
18,33,f1b4e,"Why did romantic rel end with BM, Drug problem ?",B4E,1
19,34,f1b4f,"Why did romantic rel end with BM, Violence, Ab...",B4F,1
20,35,f1b4g,"Why did romantic rel end with BM, Other?",B4G,1
21,36,f1b5a,"Last mo did you and BM, visited with friends?",B5A,1
22,37,f1b5b,"Last mo did you and BM, went out to a movie, s...",B5B,1
23,38,f1b5c,"Last mo did you and BM, ate out in a restaurant?",B5C,1
24,39,f1b5d,"Last mo did you and BM, helped each other solv...",B5D,1
25,40,f1b6a,"When last tgthr, how often did you disagree ab...",B6A,1
26,41,f1b6b,"When last tgthr, how often did you disagree ab...",B6B,1
27,42,f1b6c,"When last tgthr, how often did you disagree ab...",B6C,1
28,43,f1b6d,"When last tgthr, how often did you disagree ab...",B6D,1
29,44,f1b6e,"When last tgthr, how often did you disagree ab...",B6E,1
...,...,...,...,...,...
307,322,f1j11,"In last yr, how many wks did you spend at your...",J11,0
308,323,f1j12,"When at these jobs, how many hours per week di...",J12,0
309,324,f1j13a,Off the books or under the table work?,J13A,1
310,325,f1j13b,Work in own business?,J13B,1
311,326,f1j13c,"Selling stolen goods, selling/delivering drugs...",J13C,1
312,327,f1j13d,Other activities?,J13D,1
313,328,f1j14a,In last yr how many weeks did you engage in of...,J14A,1
314,329,f1j14b,"In last yr, how many wks did you work in your ...",J14B,1
315,330,f1j14c,In last yr how many weeks did you engage in hu...,J14C,1
316,331,f1j14d,In last yr how many wks did you engage in othe...,J14D,1
317,332,f1j15a,How many hrs/wk did you engage in off books work?,J15A,1
318,333,f1j15b,How many hrs/week did you spend in your own bu...,J15B,1
319,334,f1j15c,How many hrs/wk did you engage in hustles?,J15C,1
320,335,f1j15d,How many hrs/wk did you engage in other activi...,J15D,1
321,336,f1j16a,In last yr how much did you earn from off the ...,J16A,1
322,337,f1j16b,"In last yr, how much did you earn from your ow...",J16B,1
323,338,f1j16c,In the last yr how much did you earn from hust...,J16C,1
324,339,f1j16d,In last yr how much did you earn from other ac...,J16D,1
325,340,f1k1a,"In last yr, did you have income from public as...",K1A,1
326,341,f1k1b,"In last yr, did you have income from unemp.ins...",K1B,1
327,342,f1k1c,"In last yr, did you have income from family an...",K1C,1
328,343,f1k1d,"In last yr, did you have income from no one else?",K1D,1
329,344,f1k2a,How much money did you receive from Public ass...,K2A,1
330,345,f1k2b,How much money did you receive from Unemployme...,K2B,1
331,346,f1k2c,How much money did you receive from Family/Fri...,K2C,1
332,347,fx1k2,"In the last year, how much income did you rece...",X1K2,1
333,348,f1k3,"In last yr, what was your total hh income befo...",K3,0
334,349,f1k4,What are your mo expenses for rent or mortgage?,K4,0
335,350,f1k5,"At the end of the mo, how much money do you us...",K5,0
336,351,f1k6,Do you own a car?,K6,0

In [13]:
def find_question(q_number):
    """finds where the question number appears in the text - only if it only appears once"""
    ps_text = []
    ps_idx = []
    ps_startswith = []
    for idx, p in enumerate(ps):
        if re.match('[A-Z]\d*[A-Z]',q_number):
            if q_number in p.get_text():
                if p.get_text().lstrip().startswith(q_number+'.'):
                    ps_text.append(p.get_text().lstrip().split('.')[1])
                    ps_idx.append(idx)
                else:
                    ps_text.append(p.get_text().lstrip().split('.')[0])
                    ps_idx.append(idx)
        else:
            if q_number+"." in p.get_text():
                if p.get_text().lstrip().startswith(q_number+"."):
                    ps_text.append(p.get_text().lstrip().split('.')[1])
                    ps_idx.append(idx)
    if len(ps_idx)!=1:
        return np.nan, np.nan
    else:
        return ps_text[0].replace("\n"," ").strip(), ps_idx[0]

In [14]:
s = (find_question('B5'))
s

('I’m going to read you some things that couples often do together', 219)

In [15]:
def find_probe(q_number):
    probe = re.findall('[A-Z]{,1}\d{,2}', q_number)[0]
    return find_question(probe)[0]

In [17]:
find_probe('B5A')

'I’m going to read you some things that couples often do together'

In [ ]:
#df.drop(['probe'],axis=1,inplace=True)

In [ ]:
df

In [20]:
for i in range(len(df.question_number)):
    q_number = df.loc[i,'question_number']
    if re.match('^[A-Z]{,1}\d{,2}', q_number):
        df.loc[i,'probe'] = find_probe(q_number)
    else:
        df.loc[i,'probe'] = "None"

In [21]:
df

,position,name,varlab,question_number,multiple_answers,probe
0,15,f1a2,Were you present at the birth?,A2,0,Were you present at the birth?
1,16,f1a3,Have you held baby(ies)?,A3,0,Have you held the [baby/babies]?
2,17,f1a4,Will the baby(ies) have your last name?,A4,0,Will the (baby/babies) have your last name?
3,18,f1a4a,Did you want the baby(ies) to have your last n...,A4A,1,Will the (baby/babies) have your last name?
4,19,f1a5,Will your name be on the birth certificate?,A5,0,Will your name be on the birth certificate?
5,20,f1a5a,Did you want your name on the birth certificate?,A5A,1,Will your name be on the birth certificate?
6,21,f1a6,Do you have other biological children?,A6,0,Do you have any other biological children?
7,22,f1a6a,How many other biological children?,A6A,1,Do you have any other biological children?
8,23,f1a7,Who (does/do) the (baby/babies) look like?,A7,0,Who (does/do) the (baby/babies) look like?
9,24,cf1age,Constructed - Father's age (years),CF1AGE,1,NaN
10,25,f1b1a,How many years did you know each other before ...,B1A,1,NaN
11,26,f1b1b,How many months did you know each other before...,B1B,1,NaN
12,27,f1b2,Is respondent married to baby's mother?,B2,0,NaN
13,28,f1b3,What describes your current relationship with ...,B3,0,Which of the following statements best describ...
14,29,f1b4a,"Why did romantic rel end with BM, Financial Re...",B4A,1,Why did your romantic relationship with [BABY’...
15,30,f1b4b,"Why did romantic rel end with BM, Distance (Do...",B4B,1,Why did your romantic relationship with [BABY’...
16,31,f1b4c,"Why did romantic rel end with BM, Incarceration ?",B4C,1,Why did your romantic relationship with [BABY’...
17,32,f1b4d,"Why did romantic rel end with BM, Relationship...",B4D,1,Why did your romantic relationship with [BABY’...
18,33,f1b4e,"Why did romantic rel end with BM, Drug problem ?",B4E,1,Why did your romantic relationship with [BABY’...
19,34,f1b4f,"Why did romantic rel end with BM, Violence, Ab...",B4F,1,Why did your romantic relationship with [BABY’...
20,35,f1b4g,"Why did romantic rel end with BM, Other?",B4G,1,Why did your romantic relationship with [BABY’...
21,36,f1b5a,"Last mo did you and BM, visited with friends?",B5A,1,I’m going to read you some things that couples...
22,37,f1b5b,"Last mo did you and BM, went out to a movie, s...",B5B,1,I’m going to read you some things that couples...
23,38,f1b5c,"Last mo did you and BM, ate out in a restaurant?",B5C,1,I’m going to read you some things that couples...
24,39,f1b5d,"Last mo did you and BM, helped each other solv...",B5D,1,I’m going to read you some things that couples...
25,40,f1b6a,"When last tgthr, how often did you disagree ab...",B6A,1,The following is a list of subjects on which c...
26,41,f1b6b,"When last tgthr, how often did you disagree ab...",B6B,1,The following is a list of subjects on which c...
27,42,f1b6c,"When last tgthr, how often did you disagree ab...",B6C,1,The following is a list of subjects on which c...
28,43,f1b6d,"When last tgthr, how often did you disagree ab...",B6D,1,The following is a list of subjects on which c...
29,44,f1b6e,"When last tgthr, how often did you disagree ab...",B6E,1,The following is a list of subjects on which c...
...,...,...,...,...,...,...
307,322,f1j11,"In last yr, how many wks did you spend at your...",J11,0,"In the last 12 months, how many weeks did you ..."
308,323,f1j12,"When at these jobs, how many hours per week di...",J12,0,"When you were working at these jobs, about how..."
309,324,f1j13a,Off the books or under the table work?,J13A,1,We are interested in finding out about some wa...
310,325,f1j13b,Work in own business?,J13B,1,We are interested in finding out about some wa...
311,326,f1j13c,"Selling stolen goods, selling/delivering drugs...",J13C,1,We are interested in finding out about some wa...
312,327,f1j13d,Other activities?,J13D,1,We are interested in finding out about some wa...
313,328,f1j14a,In last yr how many weeks did you engage in of...,J14A,1,"In the last twelve months, how many weeks di..."
314,329,f1j14b,"In last yr, how many wks did you work in your ...",J14B,1,"In the last twelve months, how many weeks di..."
315,330,f1j14c,In last yr how many weeks did you engage in hu...,J14C,1,"In the last twelve months, how many weeks di..."
316,331,f1j14d,In last yr how many wks did you engage in othe...,J14D,1,"In the last twelve months, how many weeks di..."
317,332,f1j15a,How many hrs/wk did you engage in off books work?,J15A,1,About how many hours per week did you spend ...
318,333,f1j15b,How many hrs/week did you spend in your own bu...,J15B,1,About how many hours per week did you spend ...
319,334,f1j15c,How many hrs/wk did you engage in hustles?,J15C,1,About how many hours per week did you spend ...
320,335,f1j15d,How many hrs/wk did you engage in other activi...,J15D,1,About how many hours per week did you spend ...
321,336,f1j16a,In last yr how much did you earn from off the ...,J16A,1,"In the last twelve months, about how much di..."
322,337,f1j16b,"In last yr, how much did you earn from your ow...",J16B,1,"In the last twelve months, about how much di..."
323,338,f1j16c,In the last yr how much did you earn from hust...,J16C,1,"In the last twelve months, about how much di..."
324,339,f1j16d,In last yr how much did you earn from other ac...,J16D,1,"In the last twelve months, about how much di..."
325,340,f1k1a,"In last yr, did you have income from public as...",K1A,1,"In the last 12 months, did you have income fro..."
326,341,f1k1b,"In last yr, did you have income from unemp.ins...",K1B,1,"In the last 12 months, did you have income fro..."
327,342,f1k1c,"In last yr, did you have income from family an...",K1C,1,"In the last 12 months, did you have income fro..."
328,343,f1k1d,"In last yr, did you have income from no one else?",K1D,1,"In the last 12 months, did you have income fro..."
329,344,f1k2a,How much money did you receive from Public ass...,K2A,1,"In the last 12 months, about how much did you ..."
330,345,f1k2b,How much money did you receive from Unemployme...,K2B,1,"In the last 12 months, about how much did you ..."
331,346,f1k2c,How much money did you receive from Family/Fri...,K2C,1,"In the last 12 months, about how much did you ..."
332,347,fx1k2,"In the last year, how much income did you rece...",X1K2,1,NaN
333,348,f1k3,"In last yr, what was your total hh income befo...",K3,0,Thinking about your income and the income of e...
334,349,f1k4,What are your mo expenses for rent or mortgage?,K4,0,What are your monthly expenses for rent or mor...
335,350,f1k5,"At the end of the mo, how much money do you us...",K5,0,"At the end of the month, do you usually have…"
336,351,f1k6,Do you own a car?,K6,0,Do you own a car?

In [22]:
df['ps_text'], df['ps_idx'] = zip(*df['question_number'].map(find_question))

In [23]:
df[24:29]

,position,name,varlab,question_number,multiple_answers,probe,ps_text,ps_idx
24,39,f1b5d,"Last mo did you and BM, helped each other solv...",B5D,1,I’m going to read you some things that couples...,Helped each other solve a problem?,227.0
25,40,f1b6a,"When last tgthr, how often did you disagree ab...",B6A,1,The following is a list of subjects on which c...,"Money? Would you say it was often,",241.0
26,41,f1b6b,"When last tgthr, how often did you disagree ab...",B6B,1,The following is a list of subjects on which c...,Spending time together?,243.0
27,42,f1b6c,"When last tgthr, how often did you disagree ab...",B6C,1,The following is a list of subjects on which c...,Sex?,244.0
28,43,f1b6d,"When last tgthr, how often did you disagree ab...",B6D,1,The following is a list of subjects on which c...,The pregnancy?,245.0

In [24]:
np.isnan(df.ps_idx).sum() #number of questions where the question number doesn't appear or appears more than once

93

In [25]:
print(df.ps_text[16])
print(df.ps_idx[16])

B4C      INCARCERATION
207.0

In [26]:
#get index of <p> tag for the next question so we can split the questions (can't just shift because some questions have more than one answer or missing values)
all_idx=np.array(df.ps_idx)
all_idx=all_idx[~np.isnan(all_idx)]
all_idx=np.append(all_idx, [len(ps)])
df['ps_idx_next']=df.ps_idx.apply(lambda x: all_idx[all_idx > x].min() if ~np.isnan(x) else np.nan)

In [27]:
df[42:43]

,position,name,varlab,question_number,multiple_answers,probe,ps_text,ps_idx,ps_idx_next
42,57,f1b9a5,"Reasons no plan to live tgthr, Incarceration?",B9A5,1,Do you and [BABY’S MOTHER] have plans to live ...,B9A5 INCARCERATION,293.0,294.0

In [32]:
a3=ps[105:110]
a3

[<p class="MsoNormal" style="line-height:150%;text-autospace:none"><b><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'>A2.</span></b><span style='font-size:11.0pt;line-height:150%;
 font-family:"Arial",sans-serif;color:black'> Were you present at the birth?</span></p>,
 <p class="MsoNormal" style="margin-left:1.0in;line-height:150%;text-autospace:
 none"><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'>YES................................................................ 1</span></p>,
 <p class="MsoNormal" style="margin-left:1.0in;line-height:150%;text-autospace:
 none"><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'>NO................................................................. 2</span></p>,
 <p class="MsoNormal" style="text-indent:.5in;line-height:150%;text-autospace:
 none"><span style="position:relative;z-index:251601920;left:-1px;top:11px;
 width:614px;height:14px"><img height="3" src="FF_f1_Questionnaire_2013_files/image003.gif" width="614"/></span><b><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'> </span></b></p>,
 <p class="MsoNormal" style="line-height:150%;text-autospace:none"><b><span style='font-size:11.0pt;line-height:150%;font-family:"Arial",sans-serif;
 color:black'>A3.</span></b><span style='font-size:11.0pt;line-height:150%;
 font-family:"Arial",sans-serif;color:black'> Have you held the [baby/babies]?</span></p>]

In [33]:
consequitivedots = re.compile(r'\.{3,}')

In [34]:
combined = [(p.find_previous('p').get_text() + p.get_text()) for p in a3]

In [35]:
text = ''
j = 0
for p in a3:
    print(j)
    print(p.get_text())
    text = text + ' ' + p.find_previous('p').get_text()
    j += 1

0
A2. Were you present at the birth?
1
YES................................................................ 1
2
NO................................................................. 2
3

4
A3. Have you held the [baby/babies]?

In [36]:
print(text)

   A2. Were you present at the birth? YES................................................................ 1 NO................................................................. 2

test if lowercase letter, if so grab previous p as well.

In [37]:
answers = [p for p in a3 if len(p.find_all(string = consequitivedots))>0]

In [ ]:
type(answers[0])

In [ ]:
print(answers[0].prettify())

In [ ]:
test_answers = [p for p in a3 if len(p.find_all(string = consequitivedots))>0]
for ans in test_answers:
    if re.match('^[a-z]{1}', ans.get_text().split('.')[0]):
        print(ans.find_previous('p').get_text() + ans.get_text().split('.')[0])
        print(ans.get_text().split("(")[0].split('.')[-1])
    else:
        print(ans.get_text().split('.')[0])
        print(ans.get_text().split('.')[-1])

In [38]:
def clean_text(string):
    return string.replace("\n"," ").strip()

def get_pairs(p):
    if re.match('^[a-z]{1}', p.get_text().split('..')[0]):
        if re.match('[()]{1}', p.get_text().split('..')[-1]):
            pairs = [p.find_previous('p').get_text() + ' ' + p.get_text().split('..')[0], p.get_text().split("(")[0].split('..')[-1]]
        else:
            pairs = [p.find_previous('p').get_text() + ' ' + p.get_text().split('..')[0], p.get_text().split('..')[-1]]
    else:
        if re.match('[()]{1}', p.get_text().split('.')[-1]):
            pairs = [p.get_text().split('..')[0], p.get_text().split("(")[0].split('..')[-1] ]
        else:
            pairs = [p.get_text().split('..')[0], p.get_text().split('..')[-1]]
    pairs = [clean_text(text) for text in pairs]
    return pairs
        
def get_answers(start_idx,stop_idx):
    if np.isnan(start_idx) or np.isnan(stop_idx):
        return ([],0)
    else:
        answers = [p for p in ps[int(start_idx):int(stop_idx)] if len(p.find_all(string = consequitivedots))>0]
        answers = [get_pairs(a) for a in answers]
        return(answers, len(answers))

In [49]:
df['answers'], df['n_answers'] = zip(*map(get_answers, df['ps_idx'], df['ps_idx_next']))

KeyError: 'ps_idx'

In [48]:
(df['answers'][19])

KeyError: 'answers'

In [41]:
x = 0
while x < len(df.answers):
    ans = df.answers[x]
    if len(ans) > 0:
        for y in range(len(ans)):
            df.loc[x,'val{0}'.format(y)] = ans[y][1] #create new 'val(y)' column
            df.loc[x,'lab{0}'.format(y)] = ans[y][0] #create new 'lab(y)' column
    x += 1

In [ ]:
def clean_answers(col):
    col.str.replace('.','',1)

In [42]:
values = []
for i in range(0,18):
    values = values + ['val{0}'.format(i)]
    i += 1
for v in values:
    df[v] = df[v].map(lambda x: str(x))
    df[v] = df[v].map(lambda x: x.lstrip('.').strip())

In [43]:
df['val0']

0                            1
1                            1
2                            1
3                          nan
4               1 (SKIP TO A6)
5                          nan
6                1 (GO TO A6A)
7                          nan
8                            1
9                          nan
10     1 (SKIP TO B22 ON P.14)
11     1 (SKIP TO B22 ON P.14)
12                         nan
13      1 (SKIP TO B8 ON P. 6)
14                           1
15                           2
16                           3
17                           4
18                           5
19                           6
20                           7
21                           2
22                           2
23                           2
24                           2
25                           3
26                           3
27                           3
28                           3
29                           3
                ...
307                        nan
308                        nan
309                          1
310                          1
311                          1
312                        101
313                        nan
314                        nan
315                        nan
316                        nan
317                        nan
318                        nan
319                        nan
320                        nan
321                        nan
322                        nan
323                        nan
324                        nan
325                          1
326                          2
327                          3
328             4 (SKIP TO K3)
329                        nan
330                        nan
331                        nan
332                        nan
333                          1
334                        nan
335                          1
336                          1
Name: val0, Length: 337, dtype: object

In [44]:
i = 0
while i < len(df.ps_text):
    if df.multiple_answers[i] == 1:
        df.loc[i,'val0'] = '1'
        df.loc[i,'lab0'] = 'YES'
        df.loc[i,'val1'] = '2'
        df.loc[i,'lab1'] = 'NO'
    i += 1

In [45]:
df.drop(['answers','n_answers','question_number','ps_idx','ps_idx_next'],axis=1,inplace=True)

In [46]:
df.head(20)

,position,name,varlab,multiple_answers,probe,ps_text,val0,lab0,val1,lab1,...,val52,lab52,val53,lab53,val54,lab54,val55,lab55,val56,lab56
0,15,f1a2,Were you present at the birth?,0,Were you present at the birth?,Were you present at the birth?,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,f1a3,Have you held baby(ies)?,0,Have you held the [baby/babies]?,Have you held the [baby/babies]?,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17,f1a4,Will the baby(ies) have your last name?,0,Will the (baby/babies) have your last name?,Will the (baby/babies) have your last name?,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18,f1a4a,Did you want the baby(ies) to have your last n...,1,Will the (baby/babies) have your last name?,NaN,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19,f1a5,Will your name be on the birth certificate?,0,Will your name be on the birth certificate?,Will your name be on the birth certificate?,1 (SKIP TO A6),YES,2 (GO TO A5A),NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20,f1a5a,Did you want your name on the birth certificate?,1,Will your name be on the birth certificate?,NaN,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,21,f1a6,Do you have other biological children?,0,Do you have any other biological children?,Do you have any other biological children?,1 (GO TO A6A),YES,2 (SKIP TO A7),NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22,f1a6a,How many other biological children?,1,Do you have any other biological children?,NaN,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,23,f1a7,Who (does/do) the (baby/babies) look like?,0,Who (does/do) the (baby/babies) look like?,Who (does/do) the (baby/babies) look like?,1,ME,2,BABY’S MOTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,24,cf1age,Constructed - Father's age (years),1,NaN,NaN,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,25,f1b1a,How many years did you know each other before ...,1,NaN,B1A WRITE IN YEARS oo ...,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,26,f1b1b,How many months did you know each other before...,1,NaN,B1A WRITE IN YEARS oo ...,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,27,f1b2,Is respondent married to baby's mother?,0,NaN,NaN,nan,NaN,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28,f1b3,What describes your current relationship with ...,0,Which of the following statements best describ...,Which of the following statements best describ...,1 (SKIP TO B8 ON P. 6),We are romantically involved on a steady basis,2 (SKIP TO B8 ON P. 6),We are involved in an on-again and off-again r...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,29,f1b4a,"Why did romantic rel end with BM, Financial Re...",1,Why did your romantic relationship with [BABY’...,"B4A FINANCIAL REASONS (DON’T HAVE WORK, M...",1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,30,f1b4b,"Why did romantic rel end with BM, Distance (Do...",1,Why did your romantic relationship with [BABY’...,B4B DISTANCE (DON’T LIVE IN SAME TOWN),1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,31,f1b4c,"Why did romantic rel end with BM, Incarceration ?",1,Why did your romantic relationship with [BABY’...,B4C INCARCERATION,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,32,f1b4d,"Why did romantic rel end with BM, Relationship...",1,Why did your romantic relationship with [BABY’...,"B4D RELATIONSHIP REASONS (DON’T GET ALONG,",1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,33,f1b4e,"Why did romantic rel end with BM, Drug problem ?",1,Why did your romantic relationship with [BABY’...,B4E DRUG PROBLEM,1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,34,f1b4f,"Why did romantic rel end with BM, Violence, Ab...",1,Why did your romantic relationship with [BABY’...,"B4F VIOLENCE, ABUSE",1,YES,2,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.to_csv(path_or_buf = "f1Qtext.csv")